# Generated by Django 4.2.30 on 2026-04-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('COMPANY_ADMIN', 'Company Admin'), ('CANDIDATE', 'Candidate')], default='COMPANY_ADMIN', max_length=20),
        ),
    ]
