# Generated by Django 4.2.30 on 2026-05-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='expires_at',
        ),
    ]
