# Generated by Django 4.2.30 on 2026-05-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience_max',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_min',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
