# Generated by Django 4.2.30 on 2026-05-19 13:08

from django.db import migrations, models
import django.db.models.deletion
import jobs.models.job_model


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        ('jobs', '0005_job_job_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='enterprise.location'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_code',
            field=models.CharField(default=jobs.models.job_model.generate_job_code, editable=False, max_length=10, unique=True),
        ),
    ]
