# Generated by Django 4.2.30 on 2026-05-19 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        ('jobs', '0006_job_location_new_alter_job_job_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='location',
            new_name='location_legacy',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='location_new',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location_legacy',
        ),
    ]
