# Generated by Django 4.2.30 on 2026-05-20 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_job_location_new_alter_job_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='experience_level',
        ),
    ]
