# Generated by Django 4.2.30 on 2026-05-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_restore_experience_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='experience_level',
        ),
    ]
