# Generated by Django 4.2.30 on 2026-04-27 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('primary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('current_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('total_experience_months', models.PositiveIntegerField(default=0)),
                ('current_salary_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_salary_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(default='INR', max_length=3)),
                ('salary_period', models.CharField(choices=[('YEAR', 'Year'), ('MONTH', 'Month')], default='YEAR', max_length=10)),
                ('notice_period_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('profile_completion_score', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_location', to='enterprise.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('file_mime', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='candidate.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('UNDER_REVIEW', 'Under Review'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('expected_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('notice_period', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='candidate.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_applications', to='jobs.job')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to='candidate.resume')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name_text', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(max_length=200)),
                ('employment_type', models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance')], max_length=20, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(blank=True, default=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_experiences', to='candidate.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('SECONDARY', 'Secondary'), ('SENIOR_SECONDARY', 'Senior Secondary'), ('DIPLOMA', 'Diploma'), ('BACHELORS', 'Bachelors'), ('MASTERS', 'Masters'), ('PHD', 'PhD'), ('CERTIFICATION', 'Certification')], max_length=20)),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='candidate.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], max_length=15, null=True)),
                ('years_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_skills', to='candidate.candidateprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='candidate_skills', to='enterprise.skill')),
            ],
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['candidate'], name='candidate_r_candida_9dfaba_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['candidate'], name='candidate_j_candida_f1db2c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job'], name='candidate_j_job_id_a556c6_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status'], name='candidate_j_status_c12488_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('candidate', 'job')},
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['candidate'], name='candidate_e_candida_c3f673_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['candidate', 'is_current'], name='candidate_e_candida_3311c7_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['candidate'], name='candidate_e_candida_860457_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['level'], name='candidate_e_level_471398_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateskill',
            index=models.Index(fields=['skill'], name='candidate_c_skill_i_dbd223_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateskill',
            index=models.Index(fields=['is_primary'], name='candidate_c_is_prim_1b97d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidateskill',
            unique_together={('candidate', 'skill')},
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['total_experience_months'], name='candidate_c_total_e_01d939_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['expected_salary_amount'], name='candidate_c_expecte_e2a7d1_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['notice_period_days'], name='candidate_c_notice__748b03_idx'),
        ),
    ]
