# Generated by Django 4.2.30 on 2026-04-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_jobapplication_not_shortlisted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('RESUME_VIEWED', 'Resume Viewed'), ('UNDER_REVIEW', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('NOT_SHORTLISTED', 'Not Shortlisted')], default='APPLIED', max_length=20),
        ),
    ]
