# Generated by Django 4.2.30 on 2026-04-29 06:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('candidate', '0005_candidateuser_alter_candidateprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Candidate User', 'verbose_name_plural': 'Candidate Users'},
        ),
        migrations.AddField(
            model_name='candidateuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidateuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateuser',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='candidate.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_candidates', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
