# Generated by Django 4.2.30 on 2026-04-29 06:53

import candidate.models.resume
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_alter_candidateuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to=candidate.models.resume.resume_upload_path),
        ),
    ]
