# Generated by Django 4.2.30 on 2026-05-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_alter_resume_resume_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='primary_email',
        ),
    ]
