# Generated by Django 4.2.30 on 2026-05-21 08:39

import candidate.models.resume
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        ('candidate', '0008_remove_primary_email_from_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Candidate User', 'verbose_name_plural': 'Candidate Users'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-end_year', '-start_year']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date']},
        ),
        migrations.RenameIndex(
            model_name='candidateprofile',
            new_name='idx_cand_exp',
            old_name='candidate_c_total_e_01d939_idx',
        ),
        migrations.RenameIndex(
            model_name='candidateprofile',
            new_name='idx_cand_salary',
            old_name='candidate_c_expecte_e2a7d1_idx',
        ),
        migrations.RenameIndex(
            model_name='candidateprofile',
            new_name='idx_cand_notice',
            old_name='candidate_c_notice__748b03_idx',
        ),
        migrations.RenameIndex(
            model_name='candidateskill',
            new_name='idx_cskill_skill',
            old_name='candidate_c_skill_i_dbd223_idx',
        ),
        migrations.RenameIndex(
            model_name='candidateskill',
            new_name='idx_cskill_primary',
            old_name='candidate_c_is_prim_1b97d1_idx',
        ),
        migrations.RenameIndex(
            model_name='education',
            new_name='idx_edu_candidate',
            old_name='candidate_e_candida_860457_idx',
        ),
        migrations.RenameIndex(
            model_name='education',
            new_name='idx_edu_level',
            old_name='candidate_e_level_471398_idx',
        ),
        migrations.RenameIndex(
            model_name='experience',
            new_name='idx_exp_candidate',
            old_name='candidate_e_candida_c3f673_idx',
        ),
        migrations.RenameIndex(
            model_name='experience',
            new_name='idx_exp_cand_current',
            old_name='candidate_e_candida_3311c7_idx',
        ),
        migrations.RenameIndex(
            model_name='jobapplication',
            new_name='idx_app_candidate',
            old_name='candidate_j_candida_f1db2c_idx',
        ),
        migrations.RenameIndex(
            model_name='jobapplication',
            new_name='idx_app_job',
            old_name='candidate_j_job_id_a556c6_idx',
        ),
        migrations.RenameIndex(
            model_name='jobapplication',
            new_name='idx_app_status',
            old_name='candidate_j_status_c12488_idx',
        ),
        migrations.RenameIndex(
            model_name='resume',
            new_name='idx_resume_candidate',
            old_name='candidate_r_candida_9dfaba_idx',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='primary_phone',
        ),
        migrations.RemoveField(
            model_name='candidateuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='file_url',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='about',
            field=models.TextField(blank=True, default='', help_text='Detailed bio / summary for the profile.'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='headline',
            field=models.CharField(blank=True, default='', help_text='Short tagline: "Senior Python Developer | 5 yrs exp"', max_length=300),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_picture',
            field=models.URLField(blank=True, default='', help_text='URL to profile picture (Google avatar or uploaded).', max_length=500),
        ),
        migrations.AddField(
            model_name='candidateskill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='offered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='recruiter_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='current_designation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='current_salary_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current salary in the chosen currency.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='expected_salary_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected salary in the chosen currency.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_profiles', to='enterprise.location'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile_completion_score',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='salary_period',
            field=models.CharField(choices=[('YEAR', 'Per Year'), ('MONTH', 'Per Month')], default='YEAR', max_length=10),
        ),
        migrations.AlterField(
            model_name='candidateskill',
            name='proficiency',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='INTERMEDIATE', max_length=15),
        ),
        migrations.AlterField(
            model_name='candidateuser',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='candidateuser',
            name='is_email_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.CharField(blank=True, default='', help_text='CGPA or percentage', max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(choices=[('SECONDARY', 'Secondary (10th)'), ('SENIOR_SECONDARY', 'Senior Secondary (12th)'), ('DIPLOMA', 'Diploma'), ('BACHELORS', "Bachelor's Degree"), ('MASTERS', "Master's Degree"), ('PHD', 'PhD / Doctorate'), ('CERTIFICATION', 'Certification / Course')], max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_name_text',
            field=models.CharField(default='Unknown', help_text='Free text company name', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experience',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance')], default='FULL_TIME', max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('RESUME_VIEWED', 'Resume Viewed'), ('UNDER_REVIEW', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('NOT_SHORTLISTED', 'Not Shortlisted'), ('INTERVIEW', 'Interview Scheduled'), ('OFFERED', 'Offer Extended'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file_mime',
            field=models.CharField(default='application/pdf', max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file_size_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resume',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(default='placeholder', upload_to=candidate.models.resume.resume_upload_path),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['location'], name='idx_cand_location'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['profile_completion_score', 'total_experience_months'], name='idx_cand_score_exp'),
        ),
        migrations.AddIndex(
            model_name='candidateskill',
            index=models.Index(fields=['candidate', 'is_primary'], name='idx_cskill_cand_primary'),
        ),
        migrations.AddIndex(
            model_name='candidateuser',
            index=models.Index(fields=['email', 'is_active'], name='idx_cand_email_active'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'status'], name='idx_app_job_status'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['applied_at'], name='idx_app_date'),
        ),
        migrations.AddIndex(
            model_name='savedjob',
            index=models.Index(fields=['candidate'], name='idx_saved_candidate'),
        ),
        migrations.AlterModelTable(
            name='candidateprofile',
            table='candidate_candidateprofile',
        ),
        migrations.AlterModelTable(
            name='candidateskill',
            table='candidate_candidateskill',
        ),
        migrations.AlterModelTable(
            name='education',
            table='candidate_education',
        ),
        migrations.AlterModelTable(
            name='experience',
            table='candidate_experience',
        ),
        migrations.AlterModelTable(
            name='jobapplication',
            table='candidate_jobapplication',
        ),
        migrations.AlterModelTable(
            name='resume',
            table='candidate_resume',
        ),
        migrations.AlterModelTable(
            name='savedjob',
            table='candidate_savedjob',
        ),
    ]
