# Generated by Django 4.2.30 on 2026-05-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_schema_redesign'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='candidateprofile',
            name='idx_cand_salary',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='current_salary_amount',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='expected_salary_amount',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='salary_currency',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='salary_period',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='current_salary_lpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current salary in LPA (e.g. 4.50, 12.00).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='expected_salary_lpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected salary in LPA (e.g. 8.00, 15.50).', max_digits=6, null=True),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['expected_salary_lpa'], name='idx_cand_salary'),
        ),
    ]
