# Generated by Django 4.2.30 on 2026-05-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_remove_salary_period'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='candidateprofile',
            name='idx_cand_score_exp',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='profile_completion_score',
        ),
    ]
