# Generated by Django 4.2.30 on 2026-05-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_remove_completion_score'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='candidateprofile',
            name='idx_cand_exp',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='total_experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['total_experience_years', 'total_experience_months'], name='idx_cand_exp'),
        ),
    ]
