# Generated by Django 4.2.30 on 2026-05-22 08:45

import candidate.models.certification
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_split_experience_years_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('completion_id', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('valid_from_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('valid_from_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('valid_to_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('valid_to_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('does_not_expire', models.BooleanField(default=False)),
                ('certificate_file', models.FileField(blank=True, help_text='Upload certificate document (PDF, PNG, JPG)', null=True, upload_to=candidate.models.certification.certification_file_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='candidate.candidateprofile')),
            ],
            options={
                'db_table': 'candidate_certification',
                'ordering': ['-valid_from_year', '-valid_from_month'],
            },
        ),
    ]
