# Generated by Django 4.2.30 on 2026-05-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0013_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Uploaded profile picture.', null=True, upload_to='candidate_profiles/'),
        ),
    ]
