# Generated by Django 4.2.30 on 2026-05-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        ('candidate', '0014_alter_candidateprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_experiences', to='enterprise.location'),
        ),
    ]
