# Generated by Django 4.2.30 on 2026-05-26 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0015_alter_experience_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='certificate_file',
        ),
    ]
