# Generated by Django 4.2.30 on 2026-05-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0016_remove_certification_certificate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='is_fresher',
            field=models.BooleanField(default=False, help_text='True if candidate has no work experience (fresher).'),
        ),
    ]
