# Generated by Django 4.2.30 on 2026-05-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0017_candidateprofile_is_fresher'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='issuing_organization',
            field=models.CharField(default='', max_length=255),
        ),
    ]
