# Generated by Django 4.2.30 on 2026-04-29 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyuser_alter_company_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Company User', 'verbose_name_plural': 'Company Users'},
        ),
        migrations.AddField(
            model_name='companyuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
