# Generated by Django 4.2.30 on 2026-05-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_companyuser_options_companyuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
