# Generated by Django 4.2.30 on 2026-05-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_benefits_company_brand_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='banner_crop_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_crop_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
