# Generated by Django 4.2.30 on 2026-05-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_APPLICATION', 'New Application'), ('STATUS_UPDATE', 'Status Update'), ('EXPIRING_SOON', 'Expiring Soon'), ('SYSTEM', 'System'), ('PROFILE_VIEW', 'Profile Viewed'), ('RESUME_DOWNLOAD', 'Resume Downloaded')], max_length=20),
        ),
    ]
