# Generated by Django 4.2.30 on 2026-05-25 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_banner_crop_data_company_logo_crop_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0013_certification'),
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='candidate_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='candidate.candidateuser'),
        ),
        migrations.AddField(
            model_name='notification',
            name='company_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='company.companyuser'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
